name: Run Gradle build on push

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Generating debug keystore and SHA1 key
        run:  |
          mkdir -p $HOME/.android
          keytool -genkey -v -keystore $HOME/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      - name: Build with Gradle
        run: ./gradlew --info build
      - name: Pass tests and checks
        run: ./gradlew check
