name: Run Gradle build on push

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build
      - name: Pass tests and checks
        run: ./gradlew check
